services:
  php:
    image: php:8.4-apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
  mysql:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=joomla
      - MYSQL_USER=joomla
      - MYSQL_PASSWORD=joomla
    volumes:
      - ./mysql-data:/var/lib/mysql
